### ISSUE TITLE
SSL Certificate seems invalid

### ISSUE THREAD

**Issue by kabutz** [aalmiray/java-champions#117]
I'm getting the error:

Your connection is not private
Attackers might be trying to steal your information from www.javachampions.org (for example, passwords, messages or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_COMMON_NAME_INVALID
This server could not prove that it is www.javachampions.org; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

[Proceed to www.javachampions.org (unsafe)](chrome-error://chromewebdata/#)

**Comment by aalmiray** [comment]
I think GitHub is having issues at the moment. Took me 4 tries to push the latest version of the site while the JReleaser build failed at 2 distinct places during the same time frame. Will have another look.

    On Thursday, January 19, 2023 at 09:56:56 PM GMT+1, kabutz ***@***.***> wrote:  
 
 


I'm getting the error:

Your connection is not private
Attackers might be trying to steal your information from www.javachampions.org (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
This server could not prove that it is www.javachampions.org; its security certificate is from *.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

Proceed to www.javachampions.org (unsafe)

**Comment by kabutz** [comment]
I think Chrome had cached the previous SSL certificate and was trying to use that. Sorry for the false alert.
