### ISSUE TITLE
Which Country should be specified? 

### ISSUE THREAD

**Issue by siruslan** [aalmiray/java-champions#53]
I was born in one country (before nomination), then migrated to another one (at the nomination), and then to another one again (after nomination). Which one should be used?  
Thanks

**Comment by aalmiray** [comment]
Good question. The official JC Directory uses the country of residence at the time of nomination/acceptance. 

Some of us want to also reflect our home country when different from the country of nomination. For many the country of nomination coincides with residence.

Currently this list only registers (at most) 2 countries at a time because well, no one else brought this issue up. 

It's up to you to choose the combination you want but your country of nomination must be one of the chosen in case that only two are displayed. If you want you can split the 3 countries using the format `home / nomination / residence`.

**Comment by siruslan** [comment]
Thank you for the clarification.
